name: safeguard_app
description: "SafeGuard — Secure Escrow Payment Platform. Premium fintech UI demo."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  intl: ^0.19.0
  http: ^1.2.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  flutterwave_standard: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/icon/icon.jpeg

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.jpeg"